<?php

declare(strict_types=1);

/**
 * This file is auto-generated. Do not edit directly.
 * Generated by gen.php
 */

namespace MicroHTML;

require_once __DIR__ . '/classes.php';

# https://developer.mozilla.org/en-US/docs/Web/HTML/Element
# Main root
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function HTML(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("html", $args);
}

# Document metadata
/** @param array<string,string|\Stringable|null|bool|int|float> $attrs */
function BASE(array $attrs = []): SelfClosingHTMLElement
{
    return new SelfClosingHTMLElement("base", $attrs);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function HEAD(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("head", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float> $attrs */
function LINK(array $attrs = []): SelfClosingHTMLElement
{
    return new SelfClosingHTMLElement("link", $attrs);
}
/** @param array<string,string|\Stringable|null|bool|int|float> $attrs */
function META(array $attrs = []): SelfClosingHTMLElement
{
    return new SelfClosingHTMLElement("meta", $attrs);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function STYLE(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("style", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function TITLE(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("title", $args);
}

# Sectioning root
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function BODY(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("body", $args);
}

# Content sectioning
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function ADDRESS(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("address", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function ARTICLE(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("article", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function ASIDE(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("aside", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function FOOTER(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("footer", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function HEADER(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("header", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function H1(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("h1", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function H2(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("h2", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function H3(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("h3", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function H4(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("h4", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function H5(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("h5", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function H6(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("h6", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function HGROUP(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("hgroup", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function MAIN(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("main", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function NAV(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("nav", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function SECTION(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("section", $args);
}

# Text content
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function BLOCKQUOTE(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("blockquote", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function DD(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("dd", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function DIR(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("dir", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function DIV(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("div", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function DL(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("dl", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function DT(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("dt", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function FIGCAPTION(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("figcaption", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function FIGURE(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("figure", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float> $attrs */
function HR(array $attrs = []): SelfClosingHTMLElement
{
    return new SelfClosingHTMLElement("hr", $attrs);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function LI(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("li", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function OL(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("ol", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function P(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("p", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function PRE(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("pre", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function UL(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("ul", $args);
}

# Inline text semantics
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function A(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("a", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function ABBR(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("abbr", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function B(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("b", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function BDI(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("bdi", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function BDO(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("bdo", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float> $attrs */
function BR(array $attrs = []): SelfClosingHTMLElement
{
    return new SelfClosingHTMLElement("br", $attrs);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function CITE(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("cite", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function CODE(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("code", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function DATA(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("data", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function DFN(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("dfn", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function EM(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("em", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function I(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("i", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function KBD(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("kbd", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function MARK(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("mark", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function Q(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("q", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function RB(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("rb", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function RP(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("rp", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function RT(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("rt", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function RTC(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("rtc", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function RUBY(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("ruby", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function S(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("s", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function SAMP(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("samp", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function SMALL(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("small", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function SPAN(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("span", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function STRONG(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("strong", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function SUB(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("sub", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function SUP(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("sup", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function TIME(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("time", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function TT(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("tt", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function U(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("u", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function VAR_(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("var", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float> $attrs */
function WBR(array $attrs = []): SelfClosingHTMLElement
{
    return new SelfClosingHTMLElement("wbr", $attrs);
}

# Image and multimedia
/** @param array<string,string|\Stringable|null|bool|int|float> $attrs */
function AREA(array $attrs = []): SelfClosingHTMLElement
{
    return new SelfClosingHTMLElement("area", $attrs);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function AUDIO(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("audio", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float> $attrs */
function IMG(array $attrs = []): SelfClosingHTMLElement
{
    return new SelfClosingHTMLElement("img", $attrs);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function MAP(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("map", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float> $attrs */
function TRACK(array $attrs = []): SelfClosingHTMLElement
{
    return new SelfClosingHTMLElement("track", $attrs);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function VIDEO(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("video", $args);
}

# Embedded content
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function APPLET(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("applet", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float> $attrs */
function EMBED(array $attrs = []): SelfClosingHTMLElement
{
    return new SelfClosingHTMLElement("embed", $attrs);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function IFRAME(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("iframe", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function NOEMBED(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("noembed", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function OBJECT(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("object", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float> $attrs */
function PARAM(array $attrs = []): SelfClosingHTMLElement
{
    return new SelfClosingHTMLElement("param", $attrs);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function PICTURE(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("picture", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float> $attrs */
function SOURCE(array $attrs = []): SelfClosingHTMLElement
{
    return new SelfClosingHTMLElement("source", $attrs);
}

# Scripting
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function CANVAS(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("canvas", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function NOSCRIPT(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("noscript", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function SCRIPT(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("script", $args);
}

# Demarcating edits
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function DEL(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("del", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function INS(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("ins", $args);
}

# Table content
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function CAPTION(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("caption", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float> $attrs */
function COL(array $attrs = []): SelfClosingHTMLElement
{
    return new SelfClosingHTMLElement("col", $attrs);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function COLGROUP(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("colgroup", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function TABLE(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("table", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function TBODY(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("tbody", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function TD(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("td", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function TFOOT(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("tfoot", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function TH(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("th", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function THEAD(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("thead", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function TR(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("tr", $args);
}

# Forms
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function BUTTON(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("button", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function DATALIST(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("datalist", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function FIELDSET(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("fieldset", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function FORM(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("form", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float> $attrs */
function INPUT(array $attrs = []): SelfClosingHTMLElement
{
    return new SelfClosingHTMLElement("input", $attrs);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function LABEL(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("label", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function LEGEND(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("legend", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function METER(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("meter", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function OPTGROUP(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("optgroup", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function OPTION(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("option", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function OUTPUT(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("output", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function PROGRESS(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("progress", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function SELECT(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("select", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function TEXTAREA(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("textarea", $args);
}

# Interactive elements
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function DETAILS(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("details", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function DIALOG(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("dialog", $args);
}
/** @param array<string,string|\Stringable|null|bool|int|float>|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float $args - attribute array or children */
function SUMMARY(array|\MicroHTML\HTMLElement|string|\Stringable|null|bool|int|float ...$args): HTMLElement
{
    return new HTMLElement("summary", $args);
}
